#!/bin/bash

if which s3cmd >/dev/null; then
    echo 's3cmd installed'
else
    sudo apt-get install s3cmd -y #install dependency: s3cmd

    s3cmd --configure #prompt the installation of s3cmd
fi

sudo cp ./s3getlist /usr/bin #copy the script to /usr/bin/ 

sudo chmod a=r+w+x /usr/bin/s3getlist   #changing the permissions to make s3getlist executable

sudo echo "export PATH=$PATH:/usr/bin" >> ~/.bashrc  #making sure that the countaining directory is in the PATH

